Formateurs:
    type: entity
    table: formateurs
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 200
            fixed: false
            column: NOM
        prenom:
            type: string
            nullable: false
            length: 200
            fixed: false
            column: PRENOM
        mail:
            type: string
            nullable: true
            length: 120
            fixed: false
            column: MAIL
    lifecycleCallbacks: {  }
