Stagem1s1:
    type: entity
    table: stagem1s1
    indexes:
        id_mat:
            columns:
                - id_mat
        id_student:
            columns:
                - id_student
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idStage:
            type: integer
            nullable: false
            unsigned: false
            column: id_stage
        idMat:
            type: integer
            nullable: false
            unsigned: false
            column: id_mat
        idStudent:
            type: integer
            nullable: false
            unsigned: false
            column: id_student
        matPemf:
            type: string
            nullable: false
            length: null
            fixed: false
            column: mat_pemf
        remarque:
            type: string
            nullable: false
            length: 200
            fixed: false
    lifecycleCallbacks: {  }
